package webpage.entity;

public enum NotificationType {
    USER_COMMENTED_ON_PROFILE,
    USER_STARTED_FOLLOWING,
    USER_COMMENTED_ON_USER_THREAD,
    FOLLOWED_USER_COMMENTS,
    GAME_POSTED_UPDATE,
    USER_COMMENTED_ON_FOLLOWED_THREAD
}
